version: '3.1'

services:
  db:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  g10:
    build: ./build
    hostname: g10
    environment:
      PASSWORD: g10
    ports:
      - "10522:22"
      - "10580:80"
  g11:
    build: ./build
    hostname: g11
    environment:
      PASSWORD: g11
    ports:
      - "11522:22"
      - "11580:80"
